# Generated by Django 5.0.4 on 2024-05-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_shipment_address_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.IntegerField(verbose_name='CVV код'),
        ),
    ]
