# Generated by Django 5.0.4 on 2024-04-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('description', models.CharField(max_length=200, verbose_name='Описание товара')),
            ],
        ),
    ]
