# Generated by Django 5.0.4 on 2024-05-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_available_in_region',
            field=models.BooleanField(default=False, verbose_name='Оффициален в России'),
        ),
    ]
