# Generated by Django 5.0.4 on 2024-05-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_brand_is_available_in_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='country',
            field=models.CharField(blank=True, choices=[('US', 'Сша'), ('FR', 'Франция'), ('CN', 'Китай'), ('RU', 'Россия'), ('GE', 'Германия'), ('IT', 'Италия'), ('JP', 'Япония')], max_length=100, verbose_name='Страна бренда'),
        ),
    ]
